# Повторение NumPy и SciPy, первое знакомство с Matplotlib и sklearn

## Numpy

In [1]:
import numpy as np

In [2]:
x = [2, 3, 4, 6]
y = np.array(x)

In [4]:
print (type(x), x)
print (type(y), y)

<class 'list'> [2, 3, 4, 6]
<class 'numpy.ndarray'> [2 3 4 6]


In [5]:
print (x[1:3])

[3, 4]


In [6]:
print (y[1:3])

[3 4]


In [7]:
print (x[[0, 2]])

TypeError: list indices must be integers or slices, not list

In [8]:
print (y[[0, 2]])

[2 4]


In [9]:
print (y[y>3])

[4 6]


In [10]:
print (x * 5)

[2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6]


In [11]:
print (y * 5)

[10 15 20 30]


In [12]:
print (x ** 2)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [13]:
print (y ** 2)

[ 4  9 16 36]


In [14]:
matrix = [[1, 2, 4], [3, 1, 0]]
nd_array = np.array(matrix)

In [15]:
print (matrix[1][2])

0


In [16]:
print (nd_array[1, 2])

0


In [17]:
print (np.random.rand())

0.18256241375897553


In [18]:
print (np.random.randn())

0.0663797150744104


In [20]:
print (np.random.rand(4))

[ 0.46413941  0.79894444  0.46844463  0.77649516]


In [21]:
print (np.random.randn(4, 5))

[[ 0.95881523 -0.07094179  0.56145714  0.56450124 -2.16761295]
 [ 1.5876546  -0.55495602  0.5530497  -1.26961771 -0.52128922]
 [ 1.27779029  0.81167427 -2.85246193 -0.03049803 -1.30033949]
 [-0.76748834 -1.36110973 -0.40343928 -0.02405969 -0.81802851]]


In [22]:
print (np.arange(0, 8, 0.1))

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3  1.4
  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9
  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1  4.2  4.3  4.4
  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5  5.6  5.7  5.8  5.9
  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9  7.   7.1  7.2  7.3  7.4
  7.5  7.6  7.7  7.8  7.9]


In [23]:
print (range(0, 8, 0.1))

TypeError: 'float' object cannot be interpreted as an integer

In [24]:
%timeit (np.arange(0, 10000))
%timeit (range(0, 10000))

22.8 µs ± 3.18 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
836 ns ± 64.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Задание по numpy
1. Напишите свой аналог np.linspace с использованием цикла и с использованием list comprehension. Сравните все три варианта по производительности
1. Сравните по производительности основные операции с массивами (array) numpy и с list


## SciPy

In [ ]:
from scipy import optimize

In [ ]:
def f(x):
    return (x[0] - 3.2) ** 2 + (x[1] - 0.1) ** 2 + 3

print f([3.2, 0.1])

In [ ]:
x_min = optimize.minimize(f, [5, 5])
print x_min

In [ ]:
print x_min.x

In [ ]:
from scipy import linalg

In [ ]:
a = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
b = np.array([2, 4, -1])

x = linalg.solve(a, b)
print x

In [ ]:
print np.dot(a, x)

In [ ]:
X = np.random.randn(4, 3)
U, D, V = linalg.svd(X)
print U.shape, D.shape, V.shape
print type(U), type(D), type(V)

## Задание по scipy
Попробуйте поменять метод оптимизации в примере решения оптимизационной задачи выше, и подобрать метод с наименьшим количеством вычислений функции. Начальное приближение оставьте тем же.

## Matplotlib

In [ ]:
%matplotlib inline

In [ ]:
from matplotlib import pylab as plt

plt.plot([1, 2, 3, 4], [1, 4, 9, 16])
plt.show()

In [ ]:
x = np.arange(-10, 10, 0.1)
y = x ** 3
plt.plot(x, y)
plt.show()

## Задание по Matplotlib
1. Добавьте подписи к осям и легенду к примеру выше (см. документацию)
1. Постройте график с 5 разными элементарными функциями и сделайте легенду к графику в TeXe
1. Сохраните рисунок в файл строчкой кода на Python

## Все вместе (numpy + scipy + matplotlib)

In [ ]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from scipy import interpolate

In [ ]:
np.random.seed(42)

In [ ]:
np.random.RandomState(42)

In [ ]:
x = np.arange(0, 10, 2)
y = np.exp(-x/3.0) + np.random.randn(len(x)) * 0.05

print x[:5]
print y[:5]

In [ ]:
f = interpolate.interp1d(x, y, kind='quadratic')
xnew = np.arange(0, 8, 0.1)
ynew = f(xnew)

In [ ]:
plt.plot(x, y, 'o', xnew, ynew, '-')
plt.show()

## Задание на Numpy+Matplotlib

1. Сгенерируйте массив из 500 точек на плоскости с координатами $(x, y)$, такими, что $x$ меняется от -1 до 1, а $y = 2x - 1 + \varepsilon$, где $\varepsilon \sim \mathcal{N}(0, 0.1)$
2. Сгенерируйте массив из 100 точек на плоскости с координатами $(x, y)$, такими, что $x$ меняется от -1 до 1, а $y = 1 + \varepsilon$, где $\varepsilon \sim \mathcal{N}(0, 0.1)$
3. Изобразите первый и второй массив точек на плоскости (используя два разных цвета), а также график функии $f(x) = 2x - 1$ (используя какой-нибудь третий цвет)